#!/usr/bin/env python
# coding: utf-8

# In[4]:


#Saim Khan - 100876325

#Quizgenerator.py


import time
import random
if __name__ == "__main__":
    
    while True: #Keeps fucntion in a loop
        correct = int(0)
        count = int(0)
        totalquestions = int(5)
        
        startTime = time.time() #This allows the program to time the student
        print("The quiz has started")
        
        #Calculate answers and checks if right or wrong
        while count != totalquestions:
            num1 = random.randint(0,9)
            num2 = random.randint(0,9)
            print(f"What is {num1} ** {num2}?")
            answer = int(input())
            if answer == (num1**num2):
                print("You are correct")
                correct+=1
            else:
                print(f"You are wrong!Correct answer is {num1**num2}")
            count+=1
      
        #Checks the time by subtracting end time from start time
        endTime = time.time()
        totalTime = endTime - startTime
        
        print(f"The total number of points received are {correct} out of {totalquestions}")
        print(f"Total time taken {totalTime:.2f}seconds")
        print("Do you want to retake the test?Type Y/N")
        userinput = input();
        if userinput == "N":
            break
        elif userinput == "Y":
            continue
        else:
            print("Invalid input")
            break
